jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
