jobs:
  publish:
    if: github.repository_owner == 'ViaVersion'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      name: Publish
      run: ./gradlew build modrinth publishAllPublicationsToHangar --stacktrace
name: Publish to Hangar and Modrinth
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
